[build]
  command = "pnpm prisma migrate deploy && pnpm db:seed && pnpm prisma generate && pnpm run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"
